export const SEARCH_POKEMONS = 'SEARCH_POKEMONS';
export const GET_POKEMON = 'GET_POKEMON';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_ABILITIES = 'GET_ABILITIES';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
